/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    organization: Organization
    organization_access: OrganizationAccess
    'welcome-emails': WelcomeEmail
    users: User
    'social-medias': SocialMedia
    'social-media-posts': SocialMediaPost
    policies: Policy
    acknowledgments: Acknowledgment
    flags: Flag
    flagHistory: FlagHistory
    flagComments: FlagComment
    audit_log: AuditLog
    tenants: Tenant
    'payload-jobs': PayloadJob
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {
    organization: {
      children: 'organization'
    }
    flags: {
      history: 'flagHistory'
    }
  }
  collectionsSelect: {
    organization: OrganizationSelect<false> | OrganizationSelect<true>
    organization_access: OrganizationAccessSelect<false> | OrganizationAccessSelect<true>
    'welcome-emails': WelcomeEmailsSelect<false> | WelcomeEmailsSelect<true>
    users: UsersSelect<false> | UsersSelect<true>
    'social-medias': SocialMediasSelect<false> | SocialMediasSelect<true>
    'social-media-posts': SocialMediaPostsSelect<false> | SocialMediaPostsSelect<true>
    policies: PoliciesSelect<false> | PoliciesSelect<true>
    acknowledgments: AcknowledgmentsSelect<false> | AcknowledgmentsSelect<true>
    flags: FlagsSelect<false> | FlagsSelect<true>
    flagHistory: FlagHistorySelect<false> | FlagHistorySelect<true>
    flagComments: FlagCommentsSelect<false> | FlagCommentsSelect<true>
    audit_log: AuditLogSelect<false> | AuditLogSelect<true>
    tenants: TenantsSelect<false> | TenantsSelect<true>
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: number
  }
  globals: {}
  globalsSelect: {}
  locale: null
  user: User & {
    collection: 'users'
  }
  jobs: {
    tasks: {
      flagInactiveAccounts: TaskFlagInactiveAccounts
      detectRisks: TaskDetectRisks
      inline: {
        input: unknown
        output: unknown
      }
    }
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization".
 */
export interface Organization {
  id: number
  name: string
  type:
    | 'higher_education_institution'
    | 'government_agency'
    | 'healthcare_system'
    | 'corporate_enterprise'
    | 'nonprofit_organization'
    | 'division'
    | 'school_faculty'
    | 'department'
    | 'office'
    | 'program'
    | 'initiative'
    | 'other'
  parentOrg?: (number | null) | Organization
  admin?: (number | null) | User
  backupAdmins?: (number | User)[] | null
  email?: string | null
  phone?: string | null
  status?: ('active' | 'inactive' | 'pending_review') | null
  description?: string | null
  delegatedPermissions?: boolean | null
  path?: string | null
  depth?: number | null
  children?: {
    docs?: (number | Organization)[]
    hasNextPage?: boolean
    totalDocs?: number
  }
  disabled?: boolean | null
  tenant?: (number | null) | Tenant
  isPrimaryUnit?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number
  name: string
  role?: ('super_admin' | 'unit_admin' | 'social_media_manager') | null
  status?: ('active' | 'inactive' | 'rejected' | 'pending_activation') | null
  admin_policy_agreement: boolean
  date_of_last_policy_review?: string | null
  date_of_last_training?: string | null
  organizations?: (number | Organization)[] | null
  reject_reason?: string | null
  isEnabledTwoFactor?: boolean | null
  isInUseSecurePassword?: boolean | null
  isCompletedTrainingAccessibility?: boolean | null
  isCompletedTrainingRisk?: boolean | null
  isCompletedTrainingBrand?: boolean | null
  hasKnowledgeStandards?: boolean | null
  passwordUpdatedAt?: string | null
  offboardingCompleted?: boolean | null
  tenant?: (number | null) | Tenant
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  password?: string | null
}
/**
 * Organizations using the platform (universities, government, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number
  /**
   * e.g., University of North Carolina, Virginia Commonwealth University
   */
  name: string
  /**
   * e.g., unc.edu, vcu.edu
   */
  domain: string
  /**
   * Primary contact for this organization
   */
  adminContact: string
  /**
   * Main unit created automatically for this tenant
   */
  primaryUnit?: (number | null) | Organization
  governanceSettings?: {
    /**
     * Days after policy assignment to send reminders
     */
    policyReminderDays?:
      | {
          day: number
          id?: string | null
        }[]
      | null
    /**
     * Days after training assignment to escalate
     */
    trainingEscalationDays?:
      | {
          day: number
          id?: string | null
        }[]
      | null
    rollCallFrequency?: ('monthly' | 'quarterly' | 'semiannual' | 'annual') | null
    /**
     * Force password change every N days
     */
    passwordRotationDays?: number | null
  }
  status: 'active' | 'suspended' | 'archived'
  metadata?: {
    timezone?:
      | ('America/New_York' | 'America/Chicago' | 'America/Denver' | 'America/Los_Angeles')
      | null
    /**
     * Admin-only notes about this tenant
     */
    notes?: string | null
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization_access".
 */
export interface OrganizationAccess {
  id: number
  organization?: (number | null) | Organization
  user?: (number | null) | User
  type?: ('temporary' | 'permanent') | null
  start_date?: string | null
  end_date?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "welcome-emails".
 */
export interface WelcomeEmail {
  id: number
  instructions: string
  responsibilities?:
    | {
        responsibility: string
        id?: string | null
      }[]
    | null
  policyLinks?:
    | {
        id: string | null
        title: string
        url: string
      }[]
    | null
  tenant?: (number | null) | Tenant
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-medias".
 */
export interface SocialMedia {
  id: number
  name: string
  profileUrl: string
  platform: 'facebook' | 'instagram' | 'twitter' | 'linkedin' | 'tiktok' | 'youtube' | 'other'
  accountHandle?: string | null
  businessId?: string | null
  adminContactEmails?:
    | {
        email?: string | null
        id?: string | null
      }[]
    | null
  backupContactInfo?: string | null
  thirdPartyManagement?: ('yes' | 'no') | null
  thirdPartyProvider?: string | null
  thirdPartyContact?: string | null
  passwordManagementPractice?: ('Password Manager' | 'Manual' | 'Other') | null
  creationDate?: string | null
  linkedTools?: ('Hootsuite' | 'Canva' | 'Sprout' | 'Other')[] | null
  verificationStatus?: ('verified' | 'notVerified' | 'pending') | null
  platformSupportDetails?: string | null
  notes?: string | null
  contactEmail?: string | null
  contactPhone?: string | null
  organization: number | Organization
  socialMediaManagers: (number | User)[]
  primaryAdmin: number | User
  backupAdmin: number | User
  status: 'active' | 'inactive' | 'in_transition' | 'pending_approval'
  deactivationReason?: string | null
  /**
   * Automatically set if the account has no public activity for 30+ days and is Active or In Transition.
   */
  inactiveFlag?: boolean | null
  tenant?: (number | null) | Tenant
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-media-posts".
 */
export interface SocialMediaPost {
  id: number
  platform: 'youtube' | 'twitter' | 'facebook' | 'instagram' | 'linkedin' | 'tiktok' | 'other'
  socialMedia: number | SocialMedia
  /**
   * Unique identifier from the platform (e.g., tweet ID, video ID)
   */
  externalId: string
  /**
   * Author/creator of the post
   */
  author: string
  /**
   * Author ID from the platform
   */
  authorId?: string | null
  /**
   * Text content of the post
   */
  content: string
  /**
   * Direct link to the post
   */
  url: string
  /**
   * Media attachments (images, videos, etc.)
   */
  mediaUrls?:
    | {
        url?: string | null
        type?: ('image' | 'video' | 'audio' | 'document' | 'other') | null
        id?: string | null
      }[]
    | null
  /**
   * Engagement metrics from the platform
   */
  engagement?: {
    views?: number | null
    likes?: number | null
    comments?: number | null
    shares?: number | null
    retweets?: number | null
    quotes?: number | null
  }
  /**
   * When the post was published on the platform
   */
  publishedAt: string
  /**
   * When this post was scraped and stored
   */
  scrapedAt: string
  /**
   * Indicates if this is the most recent post from the account
   */
  isLatest?: boolean | null
  /**
   * Additional platform-specific metadata
   */
  metadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies".
 */
export interface Policy {
  id: number
  version?: number | null
  text?: {
    root: {
      type: string
      children: {
        type: string
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  author?: (number | null) | User
  tenant?: (number | null) | Tenant
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "acknowledgments".
 */
export interface Acknowledgment {
  id: number
  policy?: (number | null) | Policy
  user?: (number | null) | User
  tenant?: (number | null) | Tenant
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flags".
 */
export interface Flag {
  id: number
  flagType?: string | null
  affectedEntity?:
    | ({
        relationTo: 'users'
        value: number | User
      } | null)
    | ({
        relationTo: 'social-medias'
        value: number | SocialMedia
      } | null)
  organizations?: (number | Organization)[] | null
  status?: ('resolved' | 'pending' | 'not_applicable') | null
  detectionDate?: string | null
  source?: ('automated' | 'manual') | null
  lastActivity?: string | null
  history?: {
    docs?: (number | FlagHistory)[]
    hasNextPage?: boolean
    totalDocs?: number
  }
  description?: string | null
  suggestedAction?: string | null
  tenant?: (number | null) | Tenant
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flagHistory".
 */
export interface FlagHistory {
  id: number
  flag?: (number | null) | Flag
  user?: (number | null) | User
  action?: ('created' | 'status_changed' | 'comment') | null
  prevStatus?: ('resolved' | 'pending' | 'not_applicable') | null
  newStatus?: ('resolved' | 'pending' | 'not_applicable') | null
  tenant?: (number | null) | Tenant
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flagComments".
 */
export interface FlagComment {
  id: number
  flag?: (number | null) | Flag
  user?: (number | null) | User
  comment?: string | null
  tenant?: (number | null) | Tenant
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit_log".
 */
export interface AuditLog {
  id: number
  user: number | User
  action:
    | 'create'
    | 'update'
    | 'delete'
    | 'approval'
    | 'flag_resolution'
    | 'policy_acknowledgment'
    | 'user_creation'
    | 'password_recovery'
    | 'password_reset'
  entity: string
  prev?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  current?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  organizations?: (number | Organization)[] | null
  metadata?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  tenant?: (number | null) | Tenant
  document?:
    | ({
        relationTo: 'users'
        value: number | User
      } | null)
    | ({
        relationTo: 'organization'
        value: number | Organization
      } | null)
    | ({
        relationTo: 'social-medias'
        value: number | SocialMedia
      } | null)
    | ({
        relationTo: 'organization_access'
        value: number | OrganizationAccess
      } | null)
    | ({
        relationTo: 'flags'
        value: number | Flag
      } | null)
    | ({
        relationTo: 'flagComments'
        value: number | FlagComment
      } | null)
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  taskStatus?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  completedAt?: string | null
  totalTried?: number | null
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string
        completedAt: string
        taskSlug: 'inline' | 'flagInactiveAccounts' | 'detectRisks'
        taskID: string
        input?:
          | {
              [k: string]: unknown
            }
          | unknown[]
          | string
          | number
          | boolean
          | null
        output?:
          | {
              [k: string]: unknown
            }
          | unknown[]
          | string
          | number
          | boolean
          | null
        state: 'failed' | 'succeeded'
        error?:
          | {
              [k: string]: unknown
            }
          | unknown[]
          | string
          | number
          | boolean
          | null
        id?: string | null
      }[]
    | null
  taskSlug?: ('inline' | 'flagInactiveAccounts' | 'detectRisks') | null
  queue?: string | null
  waitUntil?: string | null
  processing?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number
  document?:
    | ({
        relationTo: 'organization'
        value: number | Organization
      } | null)
    | ({
        relationTo: 'organization_access'
        value: number | OrganizationAccess
      } | null)
    | ({
        relationTo: 'welcome-emails'
        value: number | WelcomeEmail
      } | null)
    | ({
        relationTo: 'users'
        value: number | User
      } | null)
    | ({
        relationTo: 'social-medias'
        value: number | SocialMedia
      } | null)
    | ({
        relationTo: 'social-media-posts'
        value: number | SocialMediaPost
      } | null)
    | ({
        relationTo: 'policies'
        value: number | Policy
      } | null)
    | ({
        relationTo: 'acknowledgments'
        value: number | Acknowledgment
      } | null)
    | ({
        relationTo: 'flags'
        value: number | Flag
      } | null)
    | ({
        relationTo: 'flagHistory'
        value: number | FlagHistory
      } | null)
    | ({
        relationTo: 'flagComments'
        value: number | FlagComment
      } | null)
    | ({
        relationTo: 'audit_log'
        value: number | AuditLog
      } | null)
    | ({
        relationTo: 'tenants'
        value: number | Tenant
      } | null)
    | ({
        relationTo: 'payload-jobs'
        value: number | PayloadJob
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: number | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number
  user: {
    relationTo: 'users'
    value: number | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization_select".
 */
export interface OrganizationSelect<T extends boolean = true> {
  name?: T
  type?: T
  parentOrg?: T
  admin?: T
  backupAdmins?: T
  email?: T
  phone?: T
  status?: T
  description?: T
  delegatedPermissions?: T
  path?: T
  depth?: T
  children?: T
  disabled?: T
  tenant?: T
  isPrimaryUnit?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization_access_select".
 */
export interface OrganizationAccessSelect<T extends boolean = true> {
  organization?: T
  user?: T
  type?: T
  start_date?: T
  end_date?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "welcome-emails_select".
 */
export interface WelcomeEmailsSelect<T extends boolean = true> {
  instructions?: T
  responsibilities?:
    | T
    | {
        responsibility?: T
        id?: T
      }
  policyLinks?:
    | T
    | {
        id?: T
        title?: T
        url?: T
      }
  tenant?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T
  role?: T
  status?: T
  admin_policy_agreement?: T
  date_of_last_policy_review?: T
  date_of_last_training?: T
  organizations?: T
  reject_reason?: T
  isEnabledTwoFactor?: T
  isInUseSecurePassword?: T
  isCompletedTrainingAccessibility?: T
  isCompletedTrainingRisk?: T
  isCompletedTrainingBrand?: T
  hasKnowledgeStandards?: T
  passwordUpdatedAt?: T
  offboardingCompleted?: T
  tenant?: T
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-medias_select".
 */
export interface SocialMediasSelect<T extends boolean = true> {
  name?: T
  profileUrl?: T
  platform?: T
  accountHandle?: T
  businessId?: T
  adminContactEmails?:
    | T
    | {
        email?: T
        id?: T
      }
  backupContactInfo?: T
  thirdPartyManagement?: T
  thirdPartyProvider?: T
  thirdPartyContact?: T
  passwordManagementPractice?: T
  creationDate?: T
  linkedTools?: T
  verificationStatus?: T
  platformSupportDetails?: T
  notes?: T
  contactEmail?: T
  contactPhone?: T
  organization?: T
  socialMediaManagers?: T
  primaryAdmin?: T
  backupAdmin?: T
  status?: T
  deactivationReason?: T
  inactiveFlag?: T
  tenant?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-media-posts_select".
 */
export interface SocialMediaPostsSelect<T extends boolean = true> {
  platform?: T
  socialMedia?: T
  externalId?: T
  author?: T
  authorId?: T
  content?: T
  url?: T
  mediaUrls?:
    | T
    | {
        url?: T
        type?: T
        id?: T
      }
  engagement?:
    | T
    | {
        views?: T
        likes?: T
        comments?: T
        shares?: T
        retweets?: T
        quotes?: T
      }
  publishedAt?: T
  scrapedAt?: T
  isLatest?: T
  metadata?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies_select".
 */
export interface PoliciesSelect<T extends boolean = true> {
  version?: T
  text?: T
  author?: T
  tenant?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "acknowledgments_select".
 */
export interface AcknowledgmentsSelect<T extends boolean = true> {
  policy?: T
  user?: T
  tenant?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flags_select".
 */
export interface FlagsSelect<T extends boolean = true> {
  flagType?: T
  affectedEntity?: T
  organizations?: T
  status?: T
  detectionDate?: T
  source?: T
  lastActivity?: T
  history?: T
  description?: T
  suggestedAction?: T
  tenant?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flagHistory_select".
 */
export interface FlagHistorySelect<T extends boolean = true> {
  flag?: T
  user?: T
  action?: T
  prevStatus?: T
  newStatus?: T
  tenant?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flagComments_select".
 */
export interface FlagCommentsSelect<T extends boolean = true> {
  flag?: T
  user?: T
  comment?: T
  tenant?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit_log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  user?: T
  action?: T
  entity?: T
  prev?: T
  current?: T
  organizations?: T
  metadata?: T
  tenant?: T
  document?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T
  domain?: T
  adminContact?: T
  primaryUnit?: T
  governanceSettings?:
    | T
    | {
        policyReminderDays?:
          | T
          | {
              day?: T
              id?: T
            }
        trainingEscalationDays?:
          | T
          | {
              day?: T
              id?: T
            }
        rollCallFrequency?: T
        passwordRotationDays?: T
      }
  status?: T
  metadata?:
    | T
    | {
        timezone?: T
        notes?: T
      }
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T
  taskStatus?: T
  completedAt?: T
  totalTried?: T
  hasError?: T
  error?: T
  log?:
    | T
    | {
        executedAt?: T
        completedAt?: T
        taskSlug?: T
        taskID?: T
        input?: T
        output?: T
        state?: T
        error?: T
        id?: T
      }
  taskSlug?: T
  queue?: T
  waitUntil?: T
  processing?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFlagInactiveAccounts".
 */
export interface TaskFlagInactiveAccounts {
  input?: unknown
  output: {
    success: boolean
    message: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDetectRisks".
 */
export interface TaskDetectRisks {
  input?: unknown
  output: {
    success: boolean
    message: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
