export enum ComplianceTaskType {
  PASSWORD_SETUP = 'PASSWORD_SETUP',
  POLICY_ACKNOWLEDGMENT = 'POLICY_ACKNOWLEDGMENT',
  TRAINING_COMPLETION = 'TRAINING_COMPLETION',
  USER_ROLL_CALL = 'USER_ROLL_CALL',
}

export enum ComplianceTaskStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  OVERDUE = 'OVERDUE',
  ESCALATED = 'ESCALATED',
}
