export const collectionFieldLabels: Record<string, string> = {
  backupAdmin: 'Backup Admin',
  primaryAdmin: 'Primary Admin',
  organization: 'Organization',
  isAcceptedPolicies: 'Accepted Policies',
  isEnabledTwoFactor: 'Two-Factor Enabled',
  hasKnowledgeStandards: 'Knowledge Standards',
  isInUseSecurePassword: 'Secure Password',
  isCompletedTrainingRisk: 'Risk Training Completed',
  isCompletedTrainingBrand: 'Brand Training Completed',
  isCompletedTrainingAccessibility: 'Accessibility Training Completed',
  profileUrl: 'Profile Url',
  name: 'Name',
  status: 'Status',
  createdAt: 'Created At',
  id: 'ID',
  type: 'Type',
  user: 'User',
  end_date: 'End Date',
  start_date: 'Start Date',
  role: 'Role',
  email: 'Email',
  reject_reason: 'Reject Reason',
  date_of_last_training: 'Date of Last Training',
  admin_policy_agreement: 'Admin Policy Agreement',
  date_of_last_policy_review: 'Date of Last Policy Review',
  phone: 'Phone',
  disabled: 'Disabled',
  parentOrg: 'Parent Organization',
  description: 'Description',
  flagType: 'Flag Type',
  affectedEntityType: 'Affected Entity Type',
  affectedEntity: 'Affected Entity',
  source: 'Source',
  suggestedAction: 'Suggested Action',
  contactEmail: 'Contact Email',
  platform: 'Platform',
}
