export enum AuditLogActionEnum {
  Create = 'create',
  Update = 'update',
  Delete = 'delete',
  Approval = 'approval',
  FlagResolution = 'flag_resolution',
  PolicyAcknowledgement = 'policy_acknowledgment',
  UserCreation = 'user_creation',
  PasswordRecovery = 'password_recovery',
  PasswordReset = 'password_reset',
  ComplianceTasksGenerated = 'compliance_task_generated',
  TaskEscalation = 'task_escalation',
  RoleRequestApproved = 'role_request_approved',
  RoleRequestRejected = 'role_request_rejected',
  TaskCompleted = 'task_completed',
  TrainingCompleted = 'training_completed',
  PasswordSetupCompleted = 'password_setup_completed',
  RollCallCompleted = 'roll_call_completed',
}
