import { CollectionConfig, Where } from 'payload'
import { AuditLogActionEnum } from '../types/index'
import { injectTenantHook } from '@/features/tenants/hooks/inject-tenant'
import { UserRolesEnum } from '@/features/users'
import { getAccessibleOrgIdsForUserWithPayload } from '@/shared'
import {
  extractTenantId,
  superAdminOnlyDeleteAccess,
} from '@/features/tenants/plugins/collections/helpers/access-control-helpers'
import {
  getEffectiveRole,
  normalizeActiveRole,
  normalizeRoles,
} from '@/shared/utils/role-hierarchy'

export const AuditLogs: CollectionConfig = {
  slug: 'audit_log',
  access: {
    read: async ({ req }): Promise<boolean | Where> => {
      const { user, payload } = req
      if (!user) return false

      const { id } = user
      const roles = normalizeRoles(user.roles)
      const activeRole = normalizeActiveRole(user.active_role)
      const effectiveRole = getEffectiveRole(roles, activeRole)

      if (effectiveRole === UserRolesEnum.SuperAdmin) return true
      const tenantId = extractTenantId(user)
      if (!tenantId) return false

      switch (effectiveRole) {
        case UserRolesEnum.CentralAdmin:
          return { tenant: { equals: tenantId } }

        case UserRolesEnum.UnitAdmin: {
          const accessibleOrgIds = await getAccessibleOrgIdsForUserWithPayload(user, payload)
          return {
            and: [{ tenant: { equals: tenantId } }, { organizations: { in: accessibleOrgIds } }],
          }
        }

        case UserRolesEnum.SocialMediaManager:
          return {
            and: [{ tenant: { equals: tenantId } }, { user: { equals: id } }],
          }

        default:
          return false
      }
    },

    create: async ({ req }) => !!req.user,
    update: async () => false,
    delete: superAdminOnlyDeleteAccess,
  },
  fields: [
    {
      name: 'user',
      type: 'relationship',
      relationTo: 'users',
      required: true,
    },
    {
      name: 'action',
      type: 'select',
      options: [
        {
          label: 'Create',
          value: AuditLogActionEnum.Create,
        },
        { label: 'Update', value: AuditLogActionEnum.Update },
        {
          label: 'Delete',
          value: AuditLogActionEnum.Delete,
        },
        {
          label: 'Approval',
          value: AuditLogActionEnum.Approval,
        },
        {
          label: 'Flag Resolution',
          value: AuditLogActionEnum.FlagResolution,
        },
        {
          label: 'Policy Acknowledgment',
          value: AuditLogActionEnum.PolicyAcknowledgement,
        },
        {
          label: 'User Creation',
          value: AuditLogActionEnum.UserCreation,
        },
        {
          label: 'Password Recovery',
          value: AuditLogActionEnum.PasswordRecovery,
        },
        {
          label: 'Password Reset',
          value: AuditLogActionEnum.PasswordReset,
        },
        {
          label: 'Compliance Tasks Generated',
          value: AuditLogActionEnum.ComplianceTasksGenerated,
        },
        {
          label: 'Task Escalation',
          value: AuditLogActionEnum.TaskEscalation,
        },
        { label: 'Role Request Approved', value: AuditLogActionEnum.RoleRequestApproved },
        { label: 'Role Request Rejected', value: AuditLogActionEnum.RoleRequestRejected },
        { label: 'Task Completed', value: AuditLogActionEnum.TaskCompleted },
        { label: 'Training Completed', value: AuditLogActionEnum.TrainingCompleted },
        { label: 'Password Setup Completed', value: AuditLogActionEnum.PasswordSetupCompleted },
        { label: 'Roll Call Completed', value: AuditLogActionEnum.RollCallCompleted },
        { label: '2FA Confirmed', value: AuditLogActionEnum.TwoFAConfirmed },
        { label: 'Shared Password Confirmed', value: AuditLogActionEnum.SharedPasswordConfirmed },
        { label: 'User Password Confirmed', value: AuditLogActionEnum.UserPasswordConfirmed },
        { label: 'Roll Call Triggered', value: AuditLogActionEnum.RollCallTriggered },
        { label: 'Roll Call Auto Generated', value: AuditLogActionEnum.RollCallAutoGenerated },
        {
          label: 'Roll Call Auto Generation Failed',
          value: AuditLogActionEnum.RollCallAutoGenerationFailed,
        },
        {
          label: 'Roll Call Manually Generated',
          value: AuditLogActionEnum.RollCallManuallyGenerated,
        },
        {
          label: 'Flag Resolved',
          value: AuditLogActionEnum.FlagResolved,
        },
        {
          label: 'Training Tasks Generated For New Roles',
          value: AuditLogActionEnum.TrainingTasksGeneratedForNewRoles,
        },
        {
          label: 'Reminder Sent',
          value: AuditLogActionEnum.ReminderSent,
        },
        {
          label: 'Email Sent',
          value: AuditLogActionEnum.EmailSent,
        },
        {
          label: 'Email Failed',
          value: AuditLogActionEnum.EmailFailed,
        },
        {
          label: 'Task Creation Failed',
          value: AuditLogActionEnum.TaskCreationFailed,
        },
        {
          label: 'Critical Error',
          value: AuditLogActionEnum.CriticalError,
        },
        { label: 'Overdue Notice Sent', value: AuditLogActionEnum.OverdueNoticeSent },
        {
          label: 'Task Escalated to Unit Admin',
          value: AuditLogActionEnum.EscalatedToUnitAdmin,
        },
        {
          label: 'Task Escalated to Central Admin',
          value: AuditLogActionEnum.EscalatedToCentralAdmin,
        },
      ],
      required: true,
    },
    {
      name: 'entity',
      type: 'text',
      required: true,
    },
    {
      name: 'prev',
      type: 'json',
    },
    {
      name: 'current',
      type: 'json',
    },
    {
      name: 'organizations',
      type: 'relationship',
      relationTo: 'organization',
      hasMany: true,
    },
    {
      name: 'metadata',
      type: 'json',
    },
    {
      name: 'tenant',
      type: 'relationship',
      relationTo: 'tenants',
      required: false,
      hasMany: false,
      index: true,
      admin: {
        position: 'sidebar',
        readOnly: true,
      },
      hooks: {
        beforeChange: [injectTenantHook],
      },
    },
  ],
  timestamps: true,
}
