import { useParsedSearchParams } from '@/shared/utils/searchParams'
import { auditLogSearchSchema } from '@/features/audit-log/schemas'
import { DataTableFilter } from '@/shared/components/data-table'
import { AuditLogActionEnum } from '@/features/audit-log/plugins/types'
import { AuditLog, User } from '@/types/payload-types'
import { ColumnDef } from '@tanstack/table-core'
import { Badge } from '@/shared/components/ui/badge'
import { format } from 'date-fns'
import { DiffView } from '../components/diff-view'

function getActionLabel(action: AuditLogActionEnum): string {
  const labels: Record<AuditLogActionEnum, string> = {
    [AuditLogActionEnum.Create]: 'Create',
    [AuditLogActionEnum.Update]: 'Update',
    [AuditLogActionEnum.Delete]: 'Delete',
    [AuditLogActionEnum.Approval]: 'Approval',
    [AuditLogActionEnum.FlagResolution]: 'Flag Resolution',
    [AuditLogActionEnum.PolicyAcknowledgement]: 'Policy Acknowledgment',
    [AuditLogActionEnum.UserCreation]: 'User Creation',
    [AuditLogActionEnum.PasswordRecovery]: 'Password Recovery',
    [AuditLogActionEnum.PasswordReset]: 'Password Reset',
    [AuditLogActionEnum.ComplianceTasksGenerated]: 'Compliance Tasks Generated',
    [AuditLogActionEnum.TaskEscalation]: 'Task Escalation',
    [AuditLogActionEnum.RoleRequestApproved]: 'Role Request Approved',
    [AuditLogActionEnum.RoleRequestRejected]: 'Role Request Rejected',
    [AuditLogActionEnum.TaskCompleted]: 'Task Completed',
    [AuditLogActionEnum.TrainingCompleted]: 'Training Completed',
    [AuditLogActionEnum.PasswordSetupCompleted]: 'Password Setup Completed',
    [AuditLogActionEnum.RollCallCompleted]: 'Roll Call Completed',
    [AuditLogActionEnum.TwoFAConfirmed]: '2FA Confirmed',
    [AuditLogActionEnum.SharedPasswordConfirmed]: 'Shared Password Confirmed',
    [AuditLogActionEnum.UserPasswordConfirmed]: 'User Password Confirmed',
    [AuditLogActionEnum.RollCallTriggered]: 'Roll Call Triggered',
    [AuditLogActionEnum.RollCallAutoGenerated]: 'Roll Call Auto Generated',
    [AuditLogActionEnum.RollCallAutoGenerationFailed]: 'Roll Call Auto Generation Failed',
    [AuditLogActionEnum.RollCallManuallyGenerated]: 'Roll Call Manually Generated',
    [AuditLogActionEnum.FlagResolved]: 'Flag Resolved',
  }
  return labels[action] || action
}

function getActionBadgeVariant(action: string): string {
  switch (action) {
    case AuditLogActionEnum.Create:
    case AuditLogActionEnum.UserCreation:
    case AuditLogActionEnum.ComplianceTasksGenerated:
      return 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200'
    case AuditLogActionEnum.Update:
      return 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200'
    case AuditLogActionEnum.Delete:
    case AuditLogActionEnum.RoleRequestRejected:
      return 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200'
    case AuditLogActionEnum.Approval:
    case AuditLogActionEnum.RoleRequestApproved:
    case AuditLogActionEnum.TaskCompleted:
    case AuditLogActionEnum.TrainingCompleted:
    case AuditLogActionEnum.PasswordSetupCompleted:
    case AuditLogActionEnum.RollCallCompleted:
    case AuditLogActionEnum.PolicyAcknowledgement:
    case AuditLogActionEnum.TwoFAConfirmed:
    case AuditLogActionEnum.SharedPasswordConfirmed:
    case AuditLogActionEnum.UserPasswordConfirmed:
      return 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200'
    case AuditLogActionEnum.FlagResolution:
      return 'bg-teal-100 text-teal-800 dark:bg-teal-900 dark:text-teal-200'
    case AuditLogActionEnum.TaskEscalation:
      return 'bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200'
    case AuditLogActionEnum.PasswordRecovery:
    case AuditLogActionEnum.PasswordReset:
      return 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200'
    default:
      return 'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-200'
  }
}

function useAuditLogsTable({ users }: { users: User[] }) {
  const searchParams = useParsedSearchParams(auditLogSearchSchema)

  const columnFiltersDefs: DataTableFilter[] = [
    {
      id: 'entity',
      title: 'Entity',
      type: 'select',
      allowMultiple: true,
      options: [
        { value: 'users', label: 'Users' },
        { value: 'organization', label: 'Units' },
        { value: 'social-medias', label: 'Social Media Accounts' },
        { value: 'flags', label: 'Risk Flags' },
        { value: 'policies', label: 'Policies' },
        { value: 'compliance_tasks', label: 'Compliance Tasks' },
      ],
    },
    {
      id: 'action',
      title: 'Action',
      type: 'select',
      allowMultiple: true,
      options: Object.values(AuditLogActionEnum).map((action) => ({
        value: action,
        label: getActionLabel(action),
      })),
    },
    {
      id: 'user',
      title: 'Modify by',
      type: 'select',
      allowMultiple: false,
      options: users.map((user) => ({
        value: user.id.toString(),
        label: user.name,
      })),
    },
    {
      id: 'createdAt',
      type: 'date-range',
      disabledDays: 'future',
    },
  ]

  const columns: ColumnDef<AuditLog>[] = [
    {
      accessorKey: 'user',
      header: 'Modify by',
      enableColumnFilter: true,
      cell: ({ row }) => {
        const user = row.getValue('user') as User
        return <span>{user.name}</span>
      },
    },
    {
      accessorKey: 'action',
      header: 'Action',
      enableColumnFilter: true,
      cell: ({ row }) => {
        const action = row.getValue('action') as AuditLogActionEnum
        return <Badge className={getActionBadgeVariant(action)}>{getActionLabel(action)}</Badge>
      },
    },
    {
      accessorKey: 'entity',
      header: 'Entity',
      enableColumnFilter: true,
      cell: ({ row }) => {
        const entity = row.getValue('entity') as string
        return <span className="capitalize">{entity.replace(/_/g, ' ')}</span>
      },
    },
    {
      accessorKey: 'document',
      header: 'Affected Record',
      cell: ({ row }) => {
        const document = row.getValue('document') as { value: { name: string; flagType: string } }
        return <span>{document?.value?.name || document?.value?.flagType || '-'}</span>
      },
    },
    {
      accessorKey: 'createdAt',
      header: 'Created At',
      enableColumnFilter: true,
      cell: ({ row }) => {
        const createdAt = row.getValue('createdAt') as string
        return <span>{format(new Date(createdAt), 'LLL dd, y')}</span>
      },
    },
    {
      accessorKey: 'details',
      header: 'Details',
      cell: ({ row }) => {
        const log = row.original as AuditLog
        return <DiffView log={log} />
      },
    },
  ]

  return {
    columns,
    columnFiltersDefs,
    searchParams,
  }
}

export default useAuditLogsTable
