#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn ls-lint
yarn syncpack list-mismatches
yarn lint-staged
yarn type-check
yarn lint
yarn test:coverage --filter=[HEAD^1] -- -o
yarn i18n:check --filter=[HEAD^1]
