name: Release main

on:
  push:
    branches:
      - main

jobs:
  code-checks:
    name: Run code checks and quality tools
    uses: ./.github/workflows/_code_checks.yaml

  migrate:
    name: Run the migrations on the database
    uses: ./.github/workflows/_migrate.yaml
    with:
      environment: Production
    secrets:
      db_uri: ${{ secrets.DATABASE_URL }}
