name: Release main

on:
  push:
    branches:
      - main

jobs:
  code-checks:
    name: Run code checks and quality tools
    uses: ./.github/workflows/_code_checks.yaml

  migrate:
    name: Run the migrations on the database
    uses: ./.github/workflows/_migrate.yaml
    with:
      environment: Production
    secrets:
      db_uri: ${{ secrets.DATABASE_URL }}
      smtp_host: ${{ secrets.SMTP_HOST }}
      smtp_user: ${{ secrets.SMTP_USER }}
      smtp_pass: ${{ secrets.SMTP_PASS }}
      from_address: ${{ secrets.FROM_ADDRESS }}
      from_name: ${{ secrets.FROM_NAME }}
      next_public_base_url: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
      next_public_node_env: ${{ secrets.NEXT_PUBLIC_NODE_ENV }}
